apiVersion: batch/v1
kind: Job
metadata:
  name: fressian-test
spec:
  completions: 8
  parallelism: 6
  completionMode: Indexed
  template:
    metadata:
      labels:
        app: fressian-test
    spec:
      nodeSelector:
        role: worker
      restartPolicy: Never
      containers:
        - name: fressian-test-clj
          image: eclipse-temurin:21
          volumeMounts:
            - name: data-fressian
              mountPath: "/opt/data.fressian"
            - name: maven
              mountPath: "/root/.m2"
          workingDir: "/opt/data.fressian"
          command: ["bash", "-c"]
          args:
            - "bin/lc-stress-tests-map.sh"
          resources:
            limits:
              cpu: 3000m
              memory: 10Gi
      volumes:
        - name: data-fressian
          hostPath:
            path: "/home/k3s/dev/datomic/repos/data.fressian"
        - name: maven
          hostPath:
            path: "/home/k3s/.m2"